server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    #注册到zookeeper地址
    zookeeper:
      connect-string: 192.168.21.124:2181
      connect-timeout: 3000  # 连接超时（毫秒）
      session-timeout: 6000  # 会话超时（毫秒）